const {chromium}=require('playwright');
const fs=require('fs');
const assert=require('node:assert/strict');
const dir='.loop/20261006-kaniq-homepage/evidence/';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));const rows=[];
const goto=async path=>{await page.goto('http://localhost:3000'+path);await page.waitForLoadState('networkidle');};
const shot=async name=>page.screenshot({path:dir+'dev-'+name+'.png'});
const section=async(sel,name)=>{await page.locator(sel).scrollIntoViewIfNeeded();await page.locator(sel).screenshot({path:dir+'dev-'+name+'.png'});};
await goto('/en');await shot('A2-implants-7-2');
const state=async()=>({title:await page.locator('#plan-title').innerText(),sub:await page.locator('#plan-sub').innerText(),price:await page.locator('#price').innerText(),days:await page.locator('.day-label').allTextContents(),room:await page.locator('.day').first().locator('.item').last().innerText()});
const initial=await state();await page.locator('#tx-implants').focus();await page.keyboard.press('ArrowRight');assert(await page.locator('#tx-lasik').isChecked());await page.keyboard.press('Tab');await page.keyboard.press('ArrowRight');assert(await page.locator('#days-10').isChecked());await page.keyboard.press('Tab');await page.keyboard.press('ArrowLeft');assert(await page.locator('#pax-1').isChecked());await page.keyboard.press('Space');const changed=await state();assert.notEqual(initial.title,changed.title);assert.notEqual(initial.price,changed.price);assert.equal(changed.days.length,6);await shot('A2-lasik-10-1-keyboard');
await page.locator('label[for=tx-womens-health]').click();await page.locator('label[for=days-5]').click();await page.locator('label[for=pax-3]').click();await shot('A2-womens-5-3');rows.push({A2:[initial,changed,await state()],keyboard:'Tab / ArrowRight / ArrowLeft / Space passed',sameURL:page.url()});
for(const width of [1440,390]){await page.setViewportSize({width,height:width===1440?900:844});await goto('/en');const base=await state();await page.locator('#tx-implants').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');assert(await page.locator('#tx-screening').isChecked());const screen=await state();assert.deepEqual(screen.days,base.days);assert.notEqual(screen.price,base.price);await shot('A2-screening-7-2-'+width);await page.keyboard.press('Tab');await page.keyboard.press('ArrowLeft');assert(await page.locator('#days-5').isChecked());const short=await state();assert.equal(short.price,screen.price);assert.deepEqual(short.days,['D-1','D0','D1–2','D3','D4']);await shot('A2-screening-5-2-'+width);await page.keyboard.press('Tab');await page.keyboard.press('ArrowRight');await page.keyboard.press('Space');assert(await page.locator('#pax-3').isChecked());const group=await state();assert.deepEqual(group.days,short.days);assert.equal(group.price,short.price);assert.notEqual(group.room,short.room);await shot('A2-screening-5-3-'+width);rows.push({A2recipe:width,base,screen,short,group});}
for(const lang of ['en','ja','id','mn','ko']){await page.setViewportSize({width:1440,height:900});await goto('/'+lang);await shot('A3-'+lang+'-hero-bar');await page.setViewportSize({width:390,height:844});await shot('A3-'+lang+'-mobile-bar');await page.setViewportSize({width:1440,height:900});assert.equal(await page.locator('html').getAttribute('lang'),lang);assert.equal(await page.locator('.cta--messenger[href]').count(),0);assert(!/24\s*(hours?|時間|jam|цаг|시간)/i.test(await page.locator('body').innerText()));rows.push({A3:lang,h1:(await page.locator('h1').innerText()).replaceAll('\n',''),priority:await page.locator('.care-chips li').allTextContents(),messenger:await page.locator('.cta--messenger').first().innerText()});}
await goto('/en/quote');await page.locator('.lang summary').click();assert.equal(await page.locator('.lang-menu>a').count(),5);assert.equal(await page.locator('.lang-menu>span').count(),6);await page.keyboard.press('Escape');assert.equal(await page.locator('.lang').getAttribute('open'),null);await page.locator('.lang summary').click();await page.locator('.lang-menu>a[lang=ja]').click();await page.waitForURL('**/ja/quote');assert.equal(page.url(),'http://localhost:3000/ja/quote');await page.locator('.lang summary').click();await page.locator('h1').click();assert.equal(await page.locator('.lang').getAttribute('open'),null);await page.locator('.lang summary').click();await page.locator('.lang-menu>a').last().focus();await page.keyboard.press('Tab');assert.equal(await page.locator('.lang').getAttribute('open'),null);rows.push({A3switch:'Escape / outside click / focusout / quote subpath all passed'});
await goto('/en');for(const [sel,name] of [['.okrules','A5-doctor-rules'],['.recovery','A5-recovery'],['.trust-top','A4-receipt'],['.registry','A4-records'],['#trust-steps','A5-problem'],['#templates','A5-templates'],['#ambassador','A5-ambassador'],['#organizations','A5-organizations']])await section(sel,name);
assert.equal(await page.locator('.total strong').innerText(),'₩0');assert.equal(await page.locator('.record .sample').count(),4);assert.equal(await page.locator('#templates .tpl>li').count(),6);assert.equal(await page.locator('#ambassador input').count(),4);assert.equal(await page.locator('.org-list>li').count(),4);await page.locator('#give-0').focus();await page.keyboard.press('ArrowRight');assert(await page.locator('#give-1').isChecked());assert(!/[₩$€]/.test(await page.locator('.ref-preview').innerText()));await section('#ambassador','A5-ambassador-keyboard');rows.push({A4:{total:'₩0',sampleBadges:4},A5:{templates:6,giveOptions:4,steps:4,organizations:4,ambassadorKeyboard:true}});
for(const route of ['/en','/en/quote','/mn']){await goto(route);await section('.site-foot','A4-footer-'+route.replaceAll('/','-'));assert.equal(await page.locator('.reg .sample').count(),2);}
await goto('/ja');await section('.trust-top','A4-ja-receipt');assert.equal(await page.locator('.total strong').innerText(),'₩0');await section('.recovery','A5-ja-recovery');await goto('/mn');await section('#ambassador','A5-mn-ambassador');
await page.setViewportSize({width:390,height:844});await goto('/ja');await section('.recovery','A5-ja-recovery-mobile');
// Quote state transitions Q1-Q12. No real patient data is used.
await goto('/ja/quote?interest=dental');assert(await page.locator('#interest-dental').isChecked());await goto('/ja/quote?interest=bad');assert.equal(await page.locator('[name=interest]:checked').count(),0);await page.locator('button[type=submit]').click();assert.equal(await page.locator('.quote-card [role=alert]').count(),1);await page.waitForFunction(()=>document.querySelector('[name=interest]')===document.activeElement);await shot('A6-Q2-required');await page.locator('label[for=interest-dental]').click();await page.locator('button[type=submit]').click();assert.equal(await page.locator('.stepper [aria-current]').innerText(),'2. 日程');await page.locator('button[type=submit]').click();assert.equal(await page.locator('.quote-card [role=alert]').count(),1);await page.locator('[name=timing]').last().check();await page.locator('[name=pickup]').check();await page.locator('[name=stay]').selectOption('hanok');await page.locator('button[type=submit]').click();await page.locator('button[type=button]').click();assert(await page.locator('[name=timing]').last().isChecked());assert(await page.locator('[name=pickup]').isChecked());assert.equal(await page.locator('[name=stay]').inputValue(),'hanok');await page.locator('button[type=submit]').click();await page.locator('button[type=submit]').click();assert.equal(await page.locator('.quote-card [role=alert]').count(),3);await page.locator('[name=name]').fill('Test');await page.locator('[name=contact]').fill('abc');await page.locator('[name=consent]').check();await page.locator('button[type=submit]').click();assert.equal(await page.locator('.quote-card [role=alert]').count(),1);await page.locator('[name=contact]').fill('t@example.com');await shot('A6-Q8-contact-privacy');
await context.setOffline(true);await page.locator('button[type=submit]').click();await page.locator('.error').waitFor();assert.equal(await page.locator('.stepper [aria-current]').innerText(),'3. 連絡先');assert(await page.locator('button[type=submit]').isEnabled());await shot('A6-Q12-network');await context.setOffline(false);
await page.route('**/api/quote',r=>r.fulfill({status:422,contentType:'application/json',body:JSON.stringify({ok:false,errors:[{field:'timing',code:'invalid'}]})}));await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('.stepper [aria-current]')?.textContent==='2. 日程');assert.equal(await page.locator('.quote-card [role=alert]').count(),1);await page.unroute('**/api/quote');await page.locator('[name=timing]').first().check();await page.locator('button[type=submit]').click();const response=page.waitForResponse(r=>r.url().endsWith('/api/quote')&&r.request().method()==='POST');await page.locator('button[type=submit]').click();const resp=await response;assert.equal(resp.status(),200);assert.deepEqual(await resp.json(),{ok:true});await page.locator('[data-done]').waitFor();await section('[data-done]','A6-Q10-complete');assert.equal(await page.locator('form').count(),0);rows.push({A6:'Q1-Q12 passed including offline, intercepted 422, actual POST 200',response:{ok:true},done:await page.locator('[data-done]').innerText()});
const widths=[];for(const route of ['/en','/mn','/en/quote'])for(const width of [390,768,1440]){await page.setViewportSize({width,height:width===390?844:width===768?1024:900});await goto(route);for(const open of [false,true]){if(open)await page.locator('.lang summary').click();const m=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,innerWidth}));widths.push({route,width,menuOpen:open,...m});assert(m.scrollWidth<=m.innerWidth,JSON.stringify(widths.at(-1)));}await shot('A7-'+route.replaceAll('/','-')+'-'+width);}
rows.push({A7widths:widths});
await page.setViewportSize({width:1440,height:900});await goto('/en');for(let i=0;i<8;i++){await page.keyboard.press('Tab');const f=await page.evaluate(()=>{const el=document.activeElement;const s=getComputedStyle(el);return {tag:el.tagName,text:el.textContent,outline:s.outlineWidth,style:s.outlineStyle};});rows.push({A7focus:f});if(i===0||i===6)await shot('A7-focus-'+i);}await page.locator('#tx-implants').focus();const chip=await page.locator('label[for=tx-implants]').evaluate(el=>({outline:getComputedStyle(el).outlineWidth,style:getComputedStyle(el).outlineStyle}));assert.equal(chip.outline,'3px');await shot('A7-focus-chip');await page.locator('#give-0').focus();await shot('A7-focus-ambassador');await page.locator('.msgbar .cta--quote').focus();await shot('A7-focus-bar');await page.emulateMedia({reducedMotion:'reduce'});const reduced=await page.evaluate(()=>({seal:getComputedStyle(document.querySelector('.seal')).animationName,transition:getComputedStyle(document.querySelector('.chips label')).transitionDuration,scroll:getComputedStyle(document.documentElement).scrollBehavior}));assert.deepEqual(reduced,{seal:'none',transition:'0s',scroll:'auto'});rows.push({A7reduced:reduced,chipFocus:chip});await shot('A7-reduced');
assert.equal(errors.length,0);rows.push({pageErrors:errors});fs.writeFileSync(dir+'dev-browser.json',JSON.stringify(rows,null,2));console.log('A2-A7 passed; '+widths.length+' width measurements, pageErrors 0');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
