import type { Dictionary } from "./types";
const dictionary = {
  lang: "ja",
  meta: {
    title: "KANIQ · あなたの言語のホーム",
    description:
      "診療・日数・人数を選んで、回復と韓国滞在の旅程を見てみましょう。",
    quoteTitle: "KANIQ · 見積もりを始める",
    quoteDescription: "正式公開前に手順を体験できます。",
    ogAlt: "ソウルの宮殿を訪れる家族",
  },
  previewBand:
    "事前公開サイトです — 登録手続き中のため、お申し込みは保存・返信されません。",
  header: {
    skip: "本文へスキップ",
    nav: {
      care: "診療を探す",
      plan: "旅程",
      refer: "紹介",
      trust: "信頼",
    },
    language: "言語",
    phase2Soon: "12月オープン",
  },
  hero: {
    homeFor: "あなたの言葉で医療を",
    headline: ["ソウルまで2時間。", "精密検診も歯科も、", "週末で。"],
    lede: "診療・日数・人数を選んで、回復と韓国滞在の旅程を見てみましょう。",
    quoteForPlan: "この旅程で見積もりを始める",
  },
  planner: {
    legend: {
      treatment: "診療",
      days: "韓国での日数",
      travelers: "人数",
    },
    pax: {
      one: "1名",
      two: "2名",
      group: "3名以上",
    },
    title: "{name}、{n}日間",
    subtitle: {
      one: "1名、仁川到着",
      two: "2名、仁川到着",
      group: "グループ、仁川到着",
    },
    rooms: {
      one: "病院近くのホテル",
      two: "病院近くのツインルーム",
      group: "病院近くの家族向けレジデンス",
    },
    dayTitles: {
      arrive: "到着",
      treatment: "診療",
      early: "回復初期",
      culture: "回復と文化",
      free: "自由時間",
      home: "経過確認と帰国",
    },
    fixed: {
      pickup: "母語対応の運転手による空港送迎",
      escort: "コーディネーターが病院に同行",
      finalCheck: "最終診察と医療レポート",
      dropoff: "空港までの送迎と相談窓口",
    },
    tracks: {
      Move: "移動",
      Stay: "宿泊",
      Treat: "診療",
      Taste: "食事",
      Feel: "体験",
      See: "観光",
    },
    badges: {
      ok: "Doctor OK",
      from: "{n}日目から可能",
      afterDoctor: "医師の確認後",
      notUntil: "{n}日目までは待機",
    },
    priceLabel: "診療費の目安",
    priceNote: "参考価格です。個別の計画は病院が確認します。",
    feeLabel: "KANIQへの手数料",
    photoAlt: "参鶏湯の一皿",
    treatments: {
      implants: {
        name: "歯科インプラント",
        treat: "歯科でインプラントの診療",
        early: ["柔らかくぬるい参鶏湯", "韓屋で茶道", "清渓川の平坦な散歩"],
        mid: ["韓服で景福宮", "広蔵市場の食巡り", "日帰りテンプルステイ"],
        late: ["温泉の日帰り", "宿泊テンプルステイ"],
      },
      lasik: {
        name: "レーシック(LASIK)",
        treat: "眼科検査とレーシック",
        early: ["ホテルで目を閉じて休む", "室内で韓服写真", "韓定食の昼食"],
        mid: ["昼の北村と南山", "ナンタ公演", "チムジルバン"],
        late: ["漢江サイクリング", "プール"],
      },
      screening: {
        name: "健康診断・人間ドック",
        treat: "内視鏡を含む健診",
        early: ["内視鏡後のお粥", "昌徳宮の庭園", "韓屋で茶道"],
        mid: ["結果と医療レポート", "料理教室", "DDPと東大門"],
        late: ["水原城の日帰り", "韓国スパ"],
      },
      "womens-health": {
        name: "婦人科・女性の健康",
        treat: "女性医師による婦人科健診",
        early: ["静かな部屋と女性担当者", "韓屋で茶道", "寺院料理の昼食"],
        mid: ["韓方相談", "韓服で景福宮", "スパ"],
        late: ["宿泊テンプルステイ", "温泉滞在"],
      },
      fertility: {
        name: "不妊相談",
        treat: "不妊専門医との検査と相談",
        early: ["キッチン付きレジデンス", "ソウルの森の散歩", "韓定食の夕食"],
        mid: ["治療計画と遠隔相談の日程", "北村韓屋村", "伝統音楽公演"],
        late: ["加平の日帰り", "韓国スパ"],
      },
    },
  },
  care: {
    implants: "歯科インプラント",
    lasik: "レーシック(LASIK)",
    screening: "健康診断・人間ドック",
    fertility: "不妊相談",
    dental: "歯科",
    eye: "眼科",
    "womens-wellness": "女性のウェルネス",
    "womens-health": "婦人科・女性の健康",
    "serious-referral": "重症疾患の病院紹介",
    "student-checkup": "留学生健診",
  },
  local: {
    title: "あなたの言語のホーム",
    priorityTitle: "優先する診療",
    priorityCare: ["screening", "dental", "womens-wellness"],
    specialTitle: "滞在に合わせたサポート",
    special: "女性医療スタッフの指定が可能、JCB対応",
    photoAlt: "ソウルの宮殿を訪れる家族",
    photoCaption: "回復の時間も大切にする医療と文化。",
  },
  messenger: {
    channel: "LINE",
    chatOn: "{name}で相談",
    opensAtLaunch: "正式公開時に開始",
  },
  doctorOk: {
    badge: "Doctor OK",
    title: "回復に合わせた活動",
    intro: "回復ルールの例です。活動は担当医が状態に合わせて確認します。",
    caption: "診療後の日数別ルール例",
    activity: "活動",
    rows: [
      {
        activity: "チムジルバン",
        after: "レーシック(LASIK)",
        okFromDay: 3,
      },
      {
        activity: "温泉の日帰り",
        after: "歯科インプラント",
        okFromDay: 1,
      },
      {
        activity: "辛い食事",
        after: "歯科インプラント",
        okFromDay: 3,
      },
      {
        activity: "韓服で景福宮",
        after: "レーシック(LASIK)",
        okFromDay: 2,
      },
      {
        activity: "宿泊テンプルステイ",
        after: "歯科インプラント",
        okFromDay: 4,
      },
    ],
    legendOk: "医師が確認",
    legendNot: "まだ待機",
    cellOk: "可能",
    cellNot: "待機",
  },
  recovery: {
    title: "回復の一週間の例",
    intro: "診療に合わせた穏やかな活動の例です。担当医の助言に従います。",
    cols: {
      stage: "段階",
      stay: "宿泊",
      see: "観光",
      eat: "食事",
      culture: "文化",
    },
    rows: [
      {
        stage: "D0",
        note: "診療当日",
        stay: "病院近くで休む",
        see: "なし、同伴者のみ散歩",
        eat: "お粥・ぬるい食事",
        culture: "なし",
      },
      {
        stage: "D1–2",
        note: "回復初期",
        stay: "同じホテル",
        see: "平坦な散歩、1〜2時間",
        eat: "参鶏湯・韓定食・カフェ",
        culture: "茶道・室内韓服写真",
      },
      {
        stage: "D3–5",
        note: "回復と文化",
        stay: "状態に合えば韓屋へ",
        see: "南山・北村・漢江",
        eat: "市場巡り・料理教室",
        culture: "宮殿・公演・日帰り寺院",
      },
      {
        stage: "経過確認と帰国",
        note: "医師の経過確認後",
        stay: "自由",
        see: "ソウル郊外の日帰り",
        eat: "自由",
        culture: "医師の確認後のスパ・宿泊寺院",
      },
    ],
  },
  trust: {
    title: "誰が何を支払うか",
    intro: "決定前に確認できる3つの手数料原則。",
    sample: "サンプル",
    receipt: {
      title: "誰が何を支払うか",
      sub: "歯科の旅程の例",
      rows: [
        {
          what: "診療費",
          who: "病院へ支払う",
          amount: "直接来院と同じ価格",
        },
        {
          what: "送迎と宿泊",
          who: "予約前に事業者へ確認",
          amount: "見積もり通り",
        },
        {
          what: "コーディネーター・通訳・母語の相談窓口",
          who: "KANIQ",
          amount: "₩0",
        },
        {
          what: "KANIQの調整費",
          who: "病院が負担",
          amount: "患者負担なし",
        },
      ],
      total: "KANIQへのお支払い",
      seal: "患者手数料なし · KANIQ",
    },
    records: {
      title: "診療を支える人々",
      intro: "説明用の記録です。現在の提供医療機関一覧ではありません。",
      figureAlt: "医師・患者・通訳の相談",
      figureCaption: "通訳が診療に同行できます。",
      labels: {
        registration: "登録番号",
        accreditation: "認証",
        specialists: "専門医",
        languages: "対応言語",
      },
      hospitals: [
        {
          kind: "歯科インプラントと補綴、ソウル",
          specialists: "14",
          languages: "英語・日本語・モンゴル語",
          doctorBio: "補綴専門医、韓国語・英語",
        },
        {
          kind: "婦人科と不妊相談、ソウル",
          specialists: "9",
          languages: "日本語・ロシア語・インドネシア語",
          doctorBio: "産婦人科専門医、韓国語・日本語",
        },
      ],
    },
    steps: {
      title: "予定と違うことが起きたら",
      intro: "コーディネーターと順番に確認します。",
      items: [
        {
          title: "担当者に伝える",
          body: "母語で状況を説明します。",
        },
        {
          title: "病院へ連絡",
          body: "担当者が診察の確認を手配します。",
        },
        {
          title: "次の対応を相談",
          body: "選択肢と費用を確認します。",
        },
        {
          title: "問題を引き継ぐ",
          body: "解決しない場合は紛争手続きを使います。",
        },
      ],
    },
  },
  templates: {
    title: "6つの旅程から",
    intro: "6つの例から選んで見積もりを始めましょう。",
    cta: "PDF / 見積もり開始",
    items: [
      {
        name: "歯科インプラント",
        length: "7 日間",
        highlight: "回復と穏やかな文化体験",
        interest: "dental",
      },
      {
        name: "レーシック(LASIK)",
        length: "5 日間",
        highlight: "回復と穏やかな文化体験",
        interest: "eye",
      },
      {
        name: "健康診断・人間ドック",
        length: "5 日間",
        highlight: "回復と穏やかな文化体験",
        interest: "screening",
      },
      {
        name: "女性のウェルネス",
        length: "7 日間",
        highlight: "回復と穏やかな文化体験",
        interest: "womens-health",
      },
      {
        name: "不妊相談",
        length: "10 日間",
        highlight: "回復と穏やかな文化体験",
        interest: "fertility",
      },
      {
        name: "家族健診",
        length: "7 日間",
        highlight: "回復と穏やかな文化体験",
        interest: "screening",
      },
    ],
  },
  ambassador: {
    title: "紹介でつながる",
    intro: "留学生・地域の方・団体が紹介し、感謝の届け先を選べます。",
    giveLegend: "感謝の届け先",
    options: [
      {
        label: "本人",
        note: "本人で受け取る",
      },
      {
        label: "宣教支援",
        note: "宣教を支える",
      },
      {
        label: "地域基金",
        note: "地域を支える",
      },
      {
        label: "奨学金",
        note: "学生を支える",
      },
    ],
    signupNote: "加入と紹介コードは正式公開時に開始します。",
    preview: {
      title: "紹介状況",
      sample: "表示例",
      code: "紹介コード",
      cols: ["紹介者", "問い合わせ", "相談", "予約", "診療"],
      rows: [
        {
          name: "A.",
          care: "健康診断・人間ドック",
          stage: 1,
        },
        {
          name: "B.",
          care: "歯科",
          stage: 2,
        },
        {
          name: "C.",
          care: "眼科",
          stage: 3,
        },
      ],
      foot: "表示例のみ。金額や発行済みコードはありません。",
    },
  },
  organizations: {
    title: "機関との連携",
    intro: "韓国での医療につなぐ団体向けの連携モデル。",
    note: "機関からの問い合わせは正式公開時に開始します。",
    items: [
      {
        who: "大学",
        what: "学生健診と家族の訪問",
      },
      {
        who: "地域団体",
        what: "母語での医療案内",
      },
      {
        who: "宗教団体",
        what: "医療の旅と地域支援",
      },
      {
        who: "公的機関",
        what: "団体健診と協力",
      },
    ],
  },
  footer: {
    tagline: "決めるのはあなた。複雑な手続きは私たちに。",
    regMedical: "外国人患者誘致業登録",
    regTravel: "旅行業登録",
    feeTitle: "手数料の原則",
    fee: [
      "患者のKANIQ手数料は₩0",
      "直接来院と同じ診療費",
      "調整費は病院が負担",
    ],
    privacyTitle: "個人情報",
    privacy: "事前公開では入力を検証し、保存や医療機関への送信はしません。",
    disputeTitle: "紛争手続き",
    dispute: "担当者に相談し、問題対応の手順を使います。",
  },
  msgbar: {
    previewNote: "事前公開 — メッセージ相談は正式公開時に開始。",
  },
  quote: {
    title: "見積もりを始める",
    intro: "正式公開前に手順を体験できます。",
    previewNotice: "登録前のため、お申し込みは保存・返信されません。",
    steps: ["診療", "日程", "連絡先"],
    stepOf: "3ステップの{n}番目",
    interestLegend: "関心のある診療",
    timingLegend: "訪問予定",
    timing: {
      "within-3-months": "3か月以内",
      "3-6-months": "3〜6か月",
      "not-sure": "未定",
    },
    pickupLabel: "空港送迎を希望",
    stayLabel: "宿泊の希望",
    stayNone: "希望なし",
    stay: {
      "near-hospital": "病院の近く",
      hanok: "韓屋",
      "family-residence": "家族向けレジデンス",
    },
    nameLabel: "お名前",
    methodLabel: "連絡方法",
    method: {
      email: "メール",
      whatsapp: "WhatsApp",
      line: "LINE",
      messenger: "Messenger",
      kakaotalk: "KakaoTalk",
    },
    contactLabel: "連絡先",
    residenceLabel: "居住国",
    optional: "任意",
    privacy:
      "見積もり準備のため診療・日程・名前・連絡先・居住地を確認し、事前公開では保存せず、正式公開後は最長1年保存して選択した病院に提供します。",
    consentLabel: "個人情報の案内に同意します",
    next: "次へ",
    back: "戻る",
    submit: "体験を送信",
    sending: "送信中",
    errors: {
      required: "この項目を入力してください。",
      invalid: "入力内容を確認してください。",
      too_long: "入力が長すぎます。",
      network: "送信できません。もう一度お試しください。",
    },
    doneTitle: "体験が完了しました",
    donePreview: "入力を確認しました。保存されておらず、返信はありません。",
    backHome: "ホームへ",
  },
  live: {
    replyPromise: "24時間以内に返信",
    quoteDone: "お申し込みを確認します。",
  },
} satisfies Dictionary;
export default dictionary;
