import type { Dictionary } from "./types";
const dictionary = {
  lang: "ko",
  meta: {
    title: "KANIQ · 한국어를 위한 홈",
    description:
      "진료·일수·인원을 고르면 회복과 한국 여행이 하나의 여정으로 펼쳐집니다.",
    quoteTitle: "KANIQ · 견적 시작",
    quoteDescription: "출시 전 단계를 체험해 보세요.",
    ogAlt: "서울 궁궐을 방문하는 가족",
  },
  previewBand:
    "등록 절차 중인 사전 공개 사이트입니다 — 신청은 저장·회신되지 않습니다.",
  header: {
    skip: "본문으로 건너뛰기",
    nav: {
      care: "진료 찾기",
      plan: "여정",
      refer: "추천하기",
      trust: "신뢰",
    },
    language: "언어",
    phase2Soon: "12월 오픈",
  },
  hero: {
    homeFor: "내 언어로 시작하는 의료 여정",
    headline: ["동포와 유학생의 검진부터 기관 제휴까지, 한국어로."],
    lede: "진료·일수·인원을 고르면 회복과 한국 여행이 하나의 여정으로 펼쳐집니다.",
    quoteForPlan: "이 여정으로 견적 시작",
  },
  planner: {
    legend: {
      treatment: "진료",
      days: "한국 체류 일수",
      travelers: "인원",
    },
    pax: {
      one: "1명",
      two: "2명",
      group: "3명 이상",
    },
    title: "{name}, {n}일",
    subtitle: {
      one: "1명, 인천 도착",
      two: "2명, 인천 도착",
      group: "3명 이상, 인천 도착",
    },
    rooms: {
      one: "병원 근처 호텔",
      two: "병원 근처 트윈룸",
      group: "병원 근처 가족 레지던스",
    },
    dayTitles: {
      arrive: "도착",
      treatment: "진료",
      early: "회복 초기",
      culture: "회복과 문화",
      free: "자유 일정",
      home: "경과 확인과 귀국",
    },
    fixed: {
      pickup: "모국어 대응 기사의 공항 픽업",
      escort: "코디네이터의 병원 동행",
      finalCheck: "최종 진료와 의료 리포트",
      dropoff: "공항 샌딩과 후속 상담 창구",
    },
    tracks: {
      Move: "이동",
      Stay: "숙박",
      Treat: "진료",
      Taste: "식사",
      Feel: "체험",
      See: "관광",
    },
    badges: {
      ok: "Doctor OK",
      from: "{n}일차부터 가능",
      afterDoctor: "의료진 확인 후",
      notUntil: "{n}일차까지 대기",
    },
    priceLabel: "참고 진료비",
    priceNote: "참고 범위이며 병원이 개인별 계획을 확인합니다.",
    feeLabel: "KANIQ 수수료",
    photoAlt: "삼계탕 한 그릇",
    treatments: {
      implants: {
        name: "치과 임플란트",
        treat: "치과 임플란트 진료",
        early: ["부드럽고 미지근한 삼계탕", "한옥 다도", "청계천 평지 산책"],
        mid: ["한복으로 경복궁", "광장시장 식도락", "당일 템플스테이"],
        late: ["온천 당일 여행", "1박 템플스테이"],
      },
      lasik: {
        name: "라식(LASIK)",
        treat: "안과 검사와 라식",
        early: ["호텔에서 눈을 감고 휴식", "실내 한복 사진", "한정식 점심"],
        mid: ["낮의 북촌과 남산", "난타 공연", "찜질방"],
        late: ["한강 자전거", "수영장"],
      },
      screening: {
        name: "건강검진",
        treat: "수면 내시경을 포함한 검진",
        early: ["내시경 후 쌀죽", "창덕궁 후원", "한옥 다도"],
        mid: ["검진 결과와 의료 리포트", "쿠킹클래스", "DDP와 동대문"],
        late: ["수원 화성 당일 여행", "한국 스파"],
      },
      "womens-health": {
        name: "여성 건강",
        treat: "여성 의료진의 부인과 검진",
        early: ["조용한 방과 여성 코디네이터", "한옥 다도", "사찰 음식 점심"],
        mid: ["한방 상담", "한복으로 경복궁", "스파"],
        late: ["1박 템플스테이", "온천 휴식"],
      },
      fertility: {
        name: "난임 상담",
        treat: "난임 전문의 검사와 상담",
        early: ["주방이 있는 레지던스", "서울숲 산책", "한정식 저녁"],
        mid: ["진료 계획과 원격 후속 일정", "북촌 한옥마을", "국악 공연"],
        late: ["가평 당일 여행", "한국 스파"],
      },
    },
  },
  care: {
    implants: "치과 임플란트",
    lasik: "라식(LASIK)",
    screening: "건강검진",
    fertility: "난임 상담",
    dental: "치과",
    eye: "안과",
    "womens-wellness": "여성 웰니스",
    "womens-health": "여성 건강",
    "serious-referral": "중증 질환 연계",
    "student-checkup": "유학생 검진",
  },
  local: {
    title: "한국어를 위한 홈",
    priorityTitle: "우선 진료",
    priorityCare: ["student-checkup", "dental", "eye"],
    specialTitle: "방문에 맞춘 지원",
    special: "학생증 인증 할인",
    photoAlt: "서울 궁궐을 방문하는 가족",
    photoCaption: "회복할 시간을 담은 의료와 문화.",
  },
  messenger: {
    channel: "KakaoTalk",
    chatOn: "{name} 상담",
    opensAtLaunch: "출시 때 열림",
  },
  doctorOk: {
    scrub: {
      label: "회복 일차",
      todayTitle: "오늘 가능한 것",
      todayNone: "오늘은 쉬며 의료진 확인을 기다립니다",
    },
    badge: "Doctor OK",
    title: "회복에 맞춰 움직입니다",
    intro:
      "회복 규칙의 예시입니다. 활동은 담당 의료진이 상태에 맞춰 확인합니다.",
    caption: "시술 후 일수별 규칙 예시",
    activity: "활동",
    rows: [
      {
        activity: "찜질방",
        after: "라식(LASIK)",
        okFromDay: 3,
      },
      {
        activity: "온천 당일 여행",
        after: "치과 임플란트",
        okFromDay: 1,
      },
      {
        activity: "매운 음식",
        after: "치과 임플란트",
        okFromDay: 3,
      },
      {
        activity: "한복으로 경복궁",
        after: "라식(LASIK)",
        okFromDay: 2,
      },
      {
        activity: "1박 템플스테이",
        after: "치과 임플란트",
        okFromDay: 4,
      },
    ],
    legendOk: "의료진 확인",
    legendNot: "아직 대기",
    cellOk: "가능",
    cellNot: "대기",
  },
  recovery: {
    title: "회복 주간은 이렇게",
    intro: "담당 의료진의 안내에 따라 고르는 가벼운 활동의 예시입니다.",
    cols: {
      stage: "단계",
      stay: "숙소",
      see: "관광",
      eat: "식사",
      culture: "문화",
    },
    rows: [
      {
        stage: "D0",
        note: "진료 당일",
        stay: "병원 근처 숙소 휴식",
        see: "없음, 동반자는 산책 가능",
        eat: "죽·미지근한 식사",
        culture: "없음",
      },
      {
        stage: "D1–2",
        note: "회복 초기",
        stay: "같은 호텔",
        see: "평지 산책 1~2시간",
        eat: "삼계탕·한정식·카페",
        culture: "다도·실내 한복 사진",
      },
      {
        stage: "D3–5",
        note: "회복과 문화",
        stay: "상태에 맞으면 한옥 이동",
        see: "남산·북촌·한강",
        eat: "시장 투어·쿠킹클래스",
        culture: "궁궐·공연·당일 템플스테이",
      },
      {
        stage: "경과 확인과 귀국",
        note: "의료진 경과 확인 후",
        stay: "자유",
        see: "서울 근교 당일 여행",
        eat: "자유",
        culture: "의료진 확인 후 스파·1박 템플스테이",
      },
    ],
  },
  trust: {
    title: "누가 무엇을 부담하나요",
    intro: "결정 전에 확인하는 세 가지 수수료 원칙.",
    sample: "샘플",
    receipt: {
      title: "누가 무엇을 부담하나요",
      sub: "치과 여정의 예시",
      rows: [
        {
          what: "진료비",
          who: "병원에 지불",
          amount: "직접 방문과 동일 가격",
        },
        {
          what: "픽업과 숙소",
          who: "예약 전 제공자에게 확인",
          amount: "견적에 따름",
        },
        {
          what: "코디네이터·통역·모국어 상담 창구",
          who: "KANIQ",
          amount: "₩0",
        },
        {
          what: "KANIQ 조정 비용",
          who: "병원이 부담",
          amount: "환자 부담 없음",
        },
      ],
      total: "환자가 KANIQ에 내는 금액",
      seal: "환자 수수료 없음 · KANIQ",
    },
    records: {
      verify: "등록 정보 확인",
      title: "진료를 함께하는 사람들",
      intro: "설명용 기록이며 현재 이용 가능한 병원 목록은 아닙니다.",
      figureAlt: "의사·환자·통역의 상담",
      figureCaption: "통역이 진료 상담에 함께할 수 있습니다.",
      labels: {
        registration: "등록번호",
        accreditation: "인증",
        specialists: "전문의",
        languages: "대응 언어",
      },
      hospitals: [
        {
          kind: "치과 임플란트와 보철, 서울",
          specialists: "14",
          languages: "영어·일본어·몽골어",
          doctorBio: "보철과 전문의, 한국어·영어",
        },
        {
          kind: "여성 건강과 난임, 서울",
          specialists: "9",
          languages: "일본어·러시아어·인도네시아어",
          doctorBio: "산부인과 전문의, 한국어·일본어",
        },
      ],
    },
    steps: {
      title: "문제가 생겼을 때",
      intro: "코디네이터와 순서대로 확인합니다.",
      items: [
        {
          title: "담당자에게 알리기",
          body: "내 언어로 상황을 설명합니다.",
        },
        {
          title: "병원에 연락",
          body: "담당자가 의료진 확인을 연결합니다.",
        },
        {
          title: "다음 조치 협의",
          body: "가능한 선택지와 비용을 확인합니다.",
        },
        {
          title: "문제 이관",
          body: "해결되지 않으면 분쟁 절차를 이용합니다.",
        },
      ],
    },
  },
  templates: {
    title: "여섯 가지 시작점",
    intro: "여섯 여정 중 하나를 골라 견적을 시작하세요.",
    cta: "PDF 받기 / 견적 시작",
    items: [
      {
        name: "치과 임플란트",
        length: "7 일",
        highlight: "회복과 가벼운 문화 방문",
        interest: "dental",
      },
      {
        name: "라식(LASIK)",
        length: "5 일",
        highlight: "회복과 가벼운 문화 방문",
        interest: "eye",
      },
      {
        name: "건강검진",
        length: "5 일",
        highlight: "회복과 가벼운 문화 방문",
        interest: "screening",
      },
      {
        name: "여성 웰니스",
        length: "7 일",
        highlight: "회복과 가벼운 문화 방문",
        interest: "womens-health",
      },
      {
        name: "난임 상담",
        length: "10 일",
        highlight: "회복과 가벼운 문화 방문",
        interest: "fertility",
      },
      {
        name: "가족 검진",
        length: "7 일",
        highlight: "회복과 가벼운 문화 방문",
        interest: "screening",
      },
    ],
  },
  ambassador: {
    title: "소개로 이어지는 연결",
    intro: "유학생·지역 구성원·기관이 소개하고 감사 환원처를 고를 수 있습니다.",
    giveLegend: "감사 환원처 선택",
    options: [
      {
        label: "본인 수령",
        note: "직접 받기",
      },
      {
        label: "선교 후원",
        note: "선교 지원",
      },
      {
        label: "한인회 기금",
        note: "지역 공동체 지원",
      },
      {
        label: "장학",
        note: "학생 지원",
      },
    ],
    signupNote: "가입과 추천 코드 발급은 출시 때 열립니다.",
    preview: {
      giveTo: "환원처",
      title: "추천 현황",
      sample: "샘플 미리보기",
      code: "추천 코드",
      cols: ["이름", "문의", "상담", "예약", "진료"],
      rows: [
        {
          name: "A.",
          care: "건강검진",
          stage: 1,
        },
        {
          name: "B.",
          care: "치과",
          stage: 2,
        },
        {
          name: "C.",
          care: "안과",
          stage: 3,
        },
      ],
      foot: "미리보기이며 금액과 발급된 코드는 없습니다.",
    },
  },
  organizations: {
    title: "기관과 함께합니다",
    intro: "한국 의료로 연결하는 기관을 위한 협력 모델.",
    note: "기관 문의는 출시 때 열립니다.",
    items: [
      {
        who: "대학",
        what: "유학생 검진과 가족 방문",
      },
      {
        who: "한인회",
        what: "모국어 의료 안내",
      },
      {
        who: "종교 기관",
        what: "의료 여정과 공동체 지원",
      },
      {
        who: "공공기관",
        what: "단체 검진과 협력",
      },
    ],
  },
  footer: {
    tagline: "결정은 당신이. 복잡함은 카닉이.",
    regMedical: "유치업 등록번호",
    regTravel: "여행업 등록번호",
    feeTitle: "수수료 원칙",
    fee: [
      "환자 KANIQ 수수료 ₩0",
      "직접 방문과 동일한 진료비",
      "병원이 조정 비용 부담",
    ],
    privacyTitle: "개인정보",
    privacy:
      "사전 공개에서는 입력을 검증하며 저장하거나 병원으로 전달하지 않습니다.",
    disputeTitle: "분쟁 절차",
    dispute: "담당자에게 상담한 뒤 문제 대응 절차를 이용하세요.",
  },
  msgbar: {
    previewNote: "사전 공개 — 메신저 상담은 출시 때 열립니다.",
  },
  quote: {
    title: "견적 시작",
    intro: "출시 전 단계를 체험해 보세요.",
    previewNotice: "등록 전이라 신청을 저장하거나 회신하지 않습니다",
    steps: ["진료", "일정", "연락처"],
    stepOf: "3단계 중 {n}단계",
    interestLegend: "관심 진료",
    timingLegend: "방문 시기",
    timing: {
      "within-3-months": "3개월 이내",
      "3-6-months": "3~6개월",
      "not-sure": "미정",
    },
    pickupLabel: "공항 픽업 희망",
    stayLabel: "체류 희망",
    stayNone: "희망 없음",
    stay: {
      "near-hospital": "병원 근처",
      hanok: "한옥",
      "family-residence": "가족 레지던스",
    },
    nameLabel: "이름",
    methodLabel: "연락 방법",
    method: {
      email: "이메일",
      whatsapp: "WhatsApp",
      line: "LINE",
      messenger: "Messenger",
      kakaotalk: "KakaoTalk",
    },
    contactLabel: "연락처",
    residenceLabel: "거주 국가",
    optional: "선택",
    privacy:
      "견적 준비를 위해 관심 진료·일정·이름·연락처·거주지를 확인하며 사전 공개 기간에는 저장하지 않고 출시 후 최대 1년 보관하여 선택한 병원에 전달합니다.",
    consentLabel: "개인정보 고지에 동의합니다",
    next: "다음",
    back: "이전",
    submit: "체험 제출",
    sending: "전송 중",
    errors: {
      required: "필수 항목을 입력하세요.",
      invalid: "입력을 확인하세요.",
      too_long: "입력이 너무 깁니다.",
      network: "전송하지 못했습니다. 다시 시도하세요.",
    },
    doneTitle: "체험 완료",
    donePreview:
      "입력을 확인했으며 저장하지 않았습니다. 회신은 발송되지 않습니다.",
    backHome: "홈으로",
  },
  live: {
    replyPromise: "24시간 내 회신",
    quoteDone: "신청을 확인합니다.",
  },
} satisfies Dictionary;
export default dictionary;
